# Generated by Django 3.0.5 on 2021-05-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210522_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=128, verbose_name='Articulo')),
                ('talle', models.IntegerField(verbose_name='Talle')),
            ],
        ),
    ]
